# Generated by Django 5.2 on 2025-04-24 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='created_at',
            new_name='enrolled_at',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='updated_at',
        ),
    ]
